### ISSUE TITLE
Unable to output generated data points to a specified file

### ISSUE THREAD

**Issue by yetitmoves** [openmhealth/sample-data-generator#2]
I'm attempting to generate heart rate data for a 6 month time period and have the output go to a file.  Even when I remove the 'destination: console' directive, the output continues to be generated to the console and NOT the file I specify.  After reviewing my output setting below, please let me know if I am overlooking/missing something.

Many thanks in advance!

My Output Settings --

output:
  # whether to write data points to the "console" or to a "file", defaults to "console"
  file:
    # the file to write the data points to, defaults to "output.json"
    filename: output.json
    # true if the file should be appended to, false if it should be overwritten, defaults to true
    append: true

**Comment by emersonf** [comment]
Hi @yetitmoves,

The `destination` key is still required, it just needs a different value. The configuration to write to a file would look like

``` yaml
output:
  # whether to write data points to the "console" or to a "file", defaults to "console"
  destination: file
  file:
    # the file to write the data points to, defaults to "output.json"
    filename: output.json
    # true if the file should be appended to, false if it should be overwritten, defaults to true
    append: true
```

Hope that helps,
Emerson
